#!/usr/bin/env python3
"""Enforce the rhwp 200-line Rust file limit.

Existing violations are frozen in scripts/file_size_baseline.txt; no new
violation, baseline growth, or stale baseline entry is allowed. Regenerate the
baseline with `python3 scripts/check_file_size.py --write-baseline`.

Generated/data tables (font metrics, johab/PUA maps) and the accreted
wasm_api integration-test corpus are excluded -- they are not hand-maintained
source and are not refactoring targets.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

LIMIT = 200
DEFAULT_BASELINE = Path("scripts/file_size_baseline.txt")
EXCLUDE_DIRS = {".git", "target", "node_modules", "pkg", "dist", "build"}
# Substrings (posix path) for generated/data files excluded from the gate.
EXCLUDE_FILE_SUBSTR = (
    "font_metrics_data",
    "johab_map",
    "pua_oldhangul",
    "wasm_api/tests.rs",
)


def _excluded(rel: str, parts: tuple[str, ...]) -> bool:
    if any(part in EXCLUDE_DIRS for part in parts):
        return True
    return any(sub in rel for sub in EXCLUDE_FILE_SUBSTR)


def _line_count(path: Path) -> int:
    with path.open(encoding="utf-8", errors="replace") as handle:
        return sum(1 for _ in handle)


def collect_violations(root: Path, limit: int) -> dict[str, int]:
    violations: dict[str, int] = {}
    for path in root.rglob("*.rs"):
        rel = path.as_posix()
        if _excluded(rel, path.parts):
            continue
        count = _line_count(path)
        if count > limit:
            violations[rel] = count
    return dict(sorted(violations.items()))


def read_baseline(path: Path, limit: int = LIMIT) -> dict[str, int]:
    baseline: dict[str, int] = {}
    if not path.exists():
        return baseline
    for line_number, raw_line in enumerate(
        path.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            count_text, relative_path = line.split(maxsplit=1)
            count = int(count_text)
        except ValueError as exc:
            raise ValueError(
                f"{path}:{line_number}: expected '<line_count> <path>'"
            ) from exc
        if count <= limit:
            raise ValueError(f"{path}:{line_number}: baseline counts must exceed {limit}")
        if relative_path in baseline:
            raise ValueError(f"{path}:{line_number}: duplicate baseline path {relative_path}")
        baseline[relative_path] = count
    return baseline


def write_baseline(path: Path, violations: dict[str, int], limit: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    rows = [
        "# Generated by scripts/check_file_size.py --write-baseline.",
        f"# Format: <line_count> <path>; limit={limit}.",
        "",
    ]
    rows.extend(f"{count} {name}" for name, count in violations.items())
    path.write_text("\n".join(rows) + "\n", encoding="utf-8")


def _build_errors(current: dict[str, int], baseline: dict[str, int]) -> list[str]:
    errors: list[str] = []
    for path, count in current.items():
        allowed = baseline.get(path)
        if allowed is None:
            errors.append(f"new violation: {count:5d} {path}")
        elif count > allowed:
            errors.append(f"baseline grew: {allowed:5d} -> {count:5d} {path}")
    for path, allowed in baseline.items():
        if current.get(path) is None:
            errors.append(f"stale baseline entry: was {allowed:5d} {path}")
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--limit", type=int, default=LIMIT)
    parser.add_argument("--baseline", type=Path, default=DEFAULT_BASELINE)
    parser.add_argument("--write-baseline", action="store_true")
    parser.add_argument("root", nargs="?", default=".")
    args = parser.parse_args(argv)

    current = collect_violations(Path(args.root), args.limit)

    if args.write_baseline:
        write_baseline(args.baseline, current, args.limit)
        print(f"Wrote {len(current)} baseline entries to {args.baseline}.")
        return 0

    try:
        baseline = read_baseline(args.baseline, args.limit)
    except ValueError as exc:
        print(exc, file=sys.stderr)
        return 2

    errors = _build_errors(current, baseline)
    if errors:
        print(f"Rust files over {args.limit} lines are blocked unless frozen in baseline.")
        for error in errors:
            print(error)
        return 1

    print(f"File size gate passed: {len(current)} baseline violations, no growth.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
